version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - app_ingress_network


networks:
  app_ingress_network:
    driver: bridge
#    driver: overlay
#    attachable: true
volumes:
  rabbitmq_data:
  rabbitmq_logs: